- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name:  Wait for Azure VM to become reachable over SSH
      wait_for_connection:

    - name: Update all Packages
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Create Partition of Data Disk
      parted:
        device: /dev/sdb
        number: 1
        state: present

    - name: Format Data Disk to ext4
      filesystem:
        dev: /dev/sdb1
        fstype: ext4

    - name: Get Data Disk UUID
      command: blkid -s UUID -o value /dev/sdb1
      register: disk_uuid
      changed_when: false

    - name: Create Mount path
      file:
        path: /opt/unetlab/addons/qemu/
        state: directory

    - name: Create Mount Entry
      mount:
        path: /opt/unetlab/addons/qemu/
        src: "UUID={{ disk_uuid.stdout }}"
        fstype: ext4
        opts: noatime
        state: present

    - name: Add EVE-NG Apt Key
      apt_key:
        url: http://www.eve-ng.net/repo/eczema@ecze.com.gpg.key
        state: present

    - name: Add EVE-NG Repository
      apt_repository:
        repo: deb [arch=amd64]  http://www.eve-ng.net/repo xenial main

    -  name: Install a list of packages
       apt:
         update_cache: yes
         force_apt_get: yes
         pkg:
         - software-properties-common
         - eve-ng
         - python-openssl
       register: eve_pkg

    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
      when: eve_pkg.changed

    - name: Move /etc/rc.local to /etc/eve-setup.sh
      command: mv /etc/rc.local /etc/eve-setup.sh
      args:
        creates: /etc/eve-setup.sh

    - name: Update GRUB Config
      lineinfile:
        path: /etc/default/grub
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - regexp: 'GRUB_CMDLINE_LINUX_DEFAULT=.*'
          line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
        - regexp: 'GRUB_CMDLINE_LINUX=.*'
          line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0 console=ttyS1,115200"'
      register: grub_config

    - name: Update GRUB
      command: update-grub
      when: grub_config.changed

    - name: Finish Configuration
      file:
        path: /opt/ovf/.configured
        state: touch
        modification_time: preserve
        access_time: preserve
      register: configured

    - name: Reboot
      reboot:
      when: configured.changed

    - name: Copy Images
      synchronize:
        src: "{{ images_path | default('images/') }}"
        dest: /opt/unetlab/addons/qemu/
      register: images

    - name: Update Permissions
      command: /opt/unetlab/wrappers/unl_wrapper -a fixpermissions
      when: images.changed
