- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name:  Wait for VM to become reachable over SSH
      wait_for_connection:

    - name: Update all Packages
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install EVE-NG
      raw: wget -O - https://www.eve-ng.net/repo/install-eve.sh | bash -i

    - name: Copy Images
      synchronize:
        src: "{{ images_path | default('images/') }}"
        dest: /opt/unetlab/addons/qemu/
      register: images

    - name: Update Permissions
      command: /opt/unetlab/wrappers/unl_wrapper -a fixpermissions
      when: images.changed
